# Generated by Django 3.0.3 on 2020-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200401_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_are_you', models.CharField(choices=[('STUDENT', 'STUDENT'), ('LECTURER', 'LECTURER')], default='LECTURER', max_length=8)),
            ],
        ),
    ]
