# Generated by Django 3.0.3 on 2020-04-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='user',
            name='who_are_you',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('LECTURER', 'LECTURER')], default='LECTURER', max_length=8),
        ),
    ]
