# Generated by Django 3.0.3 on 2020-04-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200403_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='part',
            field=models.CharField(blank=True, choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('STUDENT', 'STUDENT'), ('LECTURER', 'LECTURER')], max_length=8),
        ),
    ]
