# Generated by Django 3.0.3 on 2020-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200403_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position_held',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('DEAN', 'Dean'), ('NONE', 'None')], default='None', max_length=4),
        ),
    ]
