# Generated by Django 3.0.3 on 2020-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_position_held'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matric_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='part',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position_held',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
