# Generated by Django 3.0.3 on 2020-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=265)),
                ('Date', models.DateTimeField()),
                ('Venue', models.CharField(blank=True, choices=[('PY102', 'PY102'), ('AJOSE', 'AJOSE'), ('1000SLT', '1000SLT'), ('ADMIN EXT RM A', 'ADMIN EXT RM A'), ('AUD1', 'AUD1'), ('AUD2', 'AUD2'), ('ODLT1', 'ODLT1'), ('ODLT2', 'ODLT2'), ('PY130', 'PY130'), ('PY238', 'PY238'), ('BOOA', 'BOOA'), ('BOOB', 'BOOB'), ('BOOC', 'BOOC')], max_length=50)),
                ('purpose', models.CharField(blank=True, choices=[('LECTURE', 'LECTURE'), ('DEFENCE', 'DEFENCE'), ('MEETING', 'MEETING'), ('SEMINAR', 'SEMINAR')], max_length=7)),
            ],
        ),
    ]
