# Generated by Django 3.0.3 on 2020-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_auto_20200419_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Venue',
            field=models.CharField(blank=True, choices=[('PY102', 'PY102'), ('AJOSE', 'AJOSE'), ('1000SLT', '1000SLT'), ('ADMIN EXT RM A', 'ADMIN EXT RM A'), ('AUD1', 'AUD1'), ('AUD2', 'AUD2'), ('ODLT1', 'ODLT1'), ('ODLT2', 'ODLT2'), ('PY130', 'PY130'), ('PY238', 'PY238'), ('BOOA', 'BOOA'), ('BOOB', 'BOOB'), ('BOOC', 'BOOC')], max_length=50),
        ),
    ]
