# Generated by Django 3.0.3 on 2020-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_auto_20200520_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Venue',
            field=models.CharField(choices=[('PY102', 'PY102'), ('ZIBAMBWE', 'ZIBAMBWE'), ('AJOSE', 'AJOSE'), ('1000SLT', '1000SLT'), ('ADMIN EXT RM A', 'ADMIN EXT RM A'), ('AUD1', 'AUD1'), ('AUD2', 'AUD2'), ('ODLT1', 'ODLT1'), ('ODLT2', 'ODLT2'), ('PY130', 'PY130'), ('PY238', 'PY238'), ('BOOA', 'BOOA'), ('BOOB', 'BOOB'), ('BOOC', 'BOOC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='purpose',
            field=models.CharField(choices=[('LECTURE', 'LECTURE'), ('DEFENCE', 'DEFENCE'), ('MEETING', 'MEETING'), ('SEMINAR', 'SEMINAR')], max_length=7),
        ),
    ]
