# Generated by Django 3.0.3 on 2020-05-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0007_auto_20200520_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=models.CharField(blank=True, choices=[('0', 'SUNDAY'), ('1', 'MONDAY'), ('2', 'TUESDAY'), ('3', 'WEDNESDAY'), ('4', 'THURSDAY'), ('5', 'FRIDAY'), ('6', 'SATURDAY')], max_length=10),
        ),
    ]
