# Generated by Django 3.0.3 on 2020-05-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0008_auto_20200522_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=models.CharField(blank=True, choices=[('0', 'MONDAY'), ('1', 'TUESDAY'), ('2', 'WEDNESDAY'), ('3', 'THURSDAY'), ('4', 'FRIDAY'), ('5', 'SATURDAY')], max_length=10),
        ),
    ]
