# Generated by Django 3.0.3 on 2020-05-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0009_auto_20200522_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=models.CharField(blank=True, choices=[('0', 'MONDAY'), ('1', 'TUESDAY'), ('2', 'WEDNESDAY'), ('3', 'THURSDAY'), ('4', 'FRIDAY'), ('5', 'SATURDAY')], max_length=10, null=True),
        ),
    ]
