# Generated by Django 3.0.3 on 2020-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0010_auto_20200525_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='Course',
        ),
        migrations.AddField(
            model_name='timetable',
            name='Name',
            field=models.CharField(default='courses', max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='purpose',
            field=models.CharField(choices=[('LECTURE', 'LECTURE'), ('DEFENCE', 'DEFENCE'), ('MEETING', 'MEETING'), ('SEMINAR', 'SEMINAR'), ('TEST', 'TEST'), ('EXAM', 'EXAM')], max_length=7),
        ),
    ]
