# Generated by Django 3.0.3 on 2020-05-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedule', '0011_auto_20200526_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedVenues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Venue', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('begin_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('purpose', models.CharField(max_length=7)),
                ('days', models.CharField(blank=True, choices=[('0', 'MONDAY'), ('1', 'TUESDAY'), ('2', 'WEDNESDAY'), ('3', 'THURSDAY'), ('4', 'FRIDAY'), ('5', 'SATURDAY')], max_length=10, null=True)),
                ('allocation_status', models.CharField(blank=True, choices=[('TEMPORARY', 'TEMPORAY'), ('PERMANENT', 'PERMANENT')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
