# Generated by Django 3.0.3 on 2020-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0013_auto_20200528_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedvenue',
            name='allocation_status',
            field=models.CharField(blank=True, choices=[('TEMPORARY', 'TEMPORARY'), ('PERMANENT', 'PERMANENT')], max_length=10, null=True),
        ),
    ]
