# Generated by Django 3.0.3 on 2020-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0014_auto_20200528_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedvenue',
            name='days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
