# Generated by Django 3.0.3 on 2020-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0016_auto_20200530_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='allocation_status',
            field=models.CharField(blank=True, choices=[('TEMPORARY', 'Temporary'), ('PERMANENT', 'Permanent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='purpose',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Defence', 'Defence'), ('Meeting', 'Meeting'), ('Seminar', 'Seminar'), ('Test', 'Test'), ('Exam', 'Exam')], max_length=7),
        ),
    ]
